### ISSUE TITLE
SDS plugin upgrade

### ISSUE THREAD

**Issue by HansSZN** [seznam/figma-plugin-sdsicons#1]
- Přidat tagy k ikonkám, aby se daly vyhledat nejen podle přesného názvu, ale i podle souvisejících výrazů (např. obálka s tagy "mail, email, envelope...")
- 16x16 info filled se nezobrazuje správně (ve squirclu není vykreslené písmeno i)
- 24x24 info filled se nezobrazuje správně (ve squirclu chybí čárka/tělo písmene i)
- filtr sekcí velikosti ikon (16x16, 24x24..) a zobrazení sekcí velikosti ikon ve výsledcích hledání

**Comment by ethanius** [comment]
Tohle všechno by asi šlo. Ovšem to první vyžaduje, aby takové informace byly součástí těch SVG, která dostávám jako zdrojová. Psát do SVG komentáře či nějaké další věci lze, jestli to ale umožňuje to, v čem je kreslíš, to netuším.

Dvě špatné ikony budou něčím rozbité, na to taky budeme muset přijít společně.

Rozdělit to na nějaké sekce podle velikostí a filtrovat i podle toho, to můžu udělat já sám.

**Comment by ethanius** [comment]
Všechno až na ty tagy u ikon je hotovo. Příště prosím každý požadavek jako samostatnou issue, aby se nestalo jako teď, že něco se odbaví, něco ne a pak to zůstane viset. Issue zavřu, tagy zadám extra.
