### ISSUE TITLE
Resize okna pluginu

### ISSUE THREAD

**Issue by StandaKaluza** [seznam/figma-plugin-sdsicons#4]
Okno pluginu je poměrně malé (je vidět max 8 ikon v jednu chvíli). Buď pevně zvětšit, nebo ideálně umožnit resize tažením.

**Comment by ethanius** [comment]
Dle absence podobné věci v dokumentaci a zmínek a požadavků jako jsou https://github.com/iconify/iconify-figma/issues/12 nebo https://spectrum.chat/figma/general/resize-plugin-windows~f4e37c8f-324b-462b-bf47-bf3b9d0b47fb jsem přesvědčený, že resizovatelné pluginy dělat nelze. Nicméně nebude problém zvětšit okno na nějakou pevnou velikost. Plus mám nejméně jeden nápad, jak by to možná šlo aspoň nějak obejít, ale to bude třeba zkusit, jestli je vůbec technicky možné.
