### ISSUE TITLE
Řazení výsledků filtru

### ISSUE THREAD

**Issue by StandaKaluza** [seznam/figma-plugin-sdsicons#6]
Podle jakého klíče se řadí ikony při zahledání ve Filtru? Hledám "mail" a první je "mail insert," následuje "mail alt1," pak třeba "mail undo" a úplně nakonec samotný "mail." Nebylo by dobré, řadit je dle abecedy?

**Comment by ethanius** [comment]
Neřadí se nijak. Respektive pořadí bude stejné jako vygeneroval importovací skript při vyrábění balíku z adresářů s SVG. Asi nebude problém seřadit je podle abecedy.
